### ISSUE TITLE
allowMethodOverride

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#1]
I recommended to add allowMethodOverride middle-ware, it cause javascript SDK access denied-- 405 Method Not Allowed.
## nodejs code:

export function allowMethodOverride(req, res, next) {
  if (req.method === 'POST' && req.body._method) {
    req.originalMethod = req.method;
    req.method = req.body._method;
    delete req.body._method;
  }
  next();
};

**Comment by lfq7413** [comment]
1. javascript SDK 通过 POST 去实现 PUT 与 DELETE 请求
2. beego 框架已经支持了 MethodOverride，但是支持形式仅限于这两种方式：通过 url 传递 method，url?_method=PUT；通过 body 以表单形式传递 method，_method:PUT
3. Parse 支持的格式为：通过 body 以 JSON 格式的数据传递，{"_method": "PUT"}
4. 因此最终的实现方式将不会与 node.js 版的类似，初步的想法是：对于有 PUT 与 DELETE 需求的资源，增加 POST 支持，在其中进行请求分发
5. 接下来将会实现该功能

**Comment by ghost** [comment]
thanks

**Comment by lfq7413** [comment]
最终使用了你在 issue #2 中提到的方法， 使用 beego.InsertFilter 实现了 MethodOverride

**Comment by ghost** [comment]
thanks, I check it with ParsePlatform/parse-dashboard

**Comment by ghost** [comment]
when parse-dashboard call a method  Content-type is "text/plain". Therefore, the code must be changed as follows:

```
func allowMethodOverride() {
    beego.InsertFilter("*", beego.BeforeRouter, func(ctx *context.Context) {
        if ctx.Input.Method() != "POST" {
            return
        }
        contentType := ctx.Input.Header("Content-type")
        if strings.HasPrefix(contentType,             "text/plain"               ) == false {
            return
        }
        if ctx.Input.RequestBody == nil || len(ctx.Input.RequestBody) == 0 {
            return
        }
        var object map[string]interface{}
        err := json.Unmarshal(ctx.Input.RequestBody, &object)
        if err != nil {
            return
        }
        if m, ok := object["_method"].(string); ok && m != "" {
            ctx.Request.Method = m
        }
    })
}
```

**Comment by lfq7413** [comment]
在 develop 分支的 commit 中解决了 "text/plain" 的问题

**Comment by umdp** [comment]
thanks, it's ok

**Comment by umdp** [comment]
in parse dash-board, uploading a file encounter the following error, It seems the error related to this issue.

XMLHttpRequest cannot load http://localhost:8080/v1/files/Screenshot%20from%202016-06-30%2023:06:44.png. Request header field X-Parse-JavaScript-Key is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by ghost** [comment]
it's ok
