### ISSUE TITLE
parse livequery -  query.fields

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#11]
key fields definition in ParseLiveQuery protocol:
The query.fields field is optional. It is an array of field names of a ParseObject. Suppose the ParseObject Player contains three fields name, id and age. If you are only interested in the change of the name field, you can set query.fields to [name]. In this situation, when the change of a Player ParseObject fulfills the subscription, only the name field will be sent to the clients instead of the full Player ParseObject.

it seems this feature is not currently implemented?

**Comment by lfq7413** [comment]
该功能已实现，但是存在几个问题，导致订阅时 fields 参数无法生效，现已修复。
该问题因为缺少测试而没有发现，后续会补充单元测试用例。

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
I will test it

**Comment by ghost** [comment]
- the LiveQuery trigger, when change another fields that is not in the query.fields 
- all fields of original object send to client

**Comment by lfq7413** [comment]
我这边没有重现这个问题，步骤如下：
1. 假设 classA 有如下一条数据
![image](https://cloud.githubusercontent.com/assets/1597563/22816214/a1d7d312-ef9b-11e6-96ed-97c484882b66.png)
2. 发送 `{"op": "connect"}` 连接 livequery ，返回 `{"clientId":1,"op":"connected"}`
3. 发送 `{"op": "subscribe","requestId": 1,"query": {"className": "classA","where": {"name": "joe"},"fields": ["name"]}}` 订阅 classA 并且限定需要字段为 `name` ，返回 `{"clientId":1,"op":"subscribed","requestId":1}`
4. 修改 `age` 字段的值，返回 `{"clientId":1,"object":{"ACL":null,"className":"classA","createdAt":"2016-12-13T03:39:38.815Z","name":"joe","objectId":"584f6d7a3cdd011c8471ca9c","updatedAt":"2017-02-10T06:08:35.479Z"},"op":"update","requestId":1}`
![image](https://cloud.githubusercontent.com/assets/1597563/22816341/78bf808c-ef9c-11e6-8d9e-7fbfbd616176.png)
5. 返回数据中并不包含 `msg` 与 `age` 字段

@gogile  是否可以发一下你的操作步骤？

**Comment by lfq7413** [comment]
我检查了一下代码，向客户端发送消息的方法为：
```golang
func (c *Client) pushEvent(eventType string) func(int, t.M, t.M) {
	return func(subscriptionId int, object, originalObject t.M) {
		response := t.M{
			"op":       eventType,
			"clientId": c.id,
		}
		if subscriptionId != 0 {
			response["requestId"] = subscriptionId
		}
		if object != nil {
			fields := []string{}
			if info, ok := c.SubscriptionInfos[subscriptionId]; ok {
				fields = info.Fields
			}
			if eventType != "delete" {
				// 仅在更新与创建时去转换操作符
				transformUpdateOperators(object, originalObject)
			}
			response["object"] = c.toObjectWithFields(object, fields)
		}
		r, err := json.Marshal(response)
		if err != nil {
			return
		}
		pushResponse(c.ws, string(r))
	}
}
```
所有类型的消息均会走这里。
当 object 不为 nil 时，必定会去过滤 fields 。

**Comment by ghost** [comment]
you right. 
Based on :

> If you are only interested in the change of the name field, you can set query.fields to [name]

I thought when defining query.fields only change in query.fields send to client.

**Comment by lfq7413** [comment]
`query.fields` 的意义为：当回调触发时，客户端仅需要这里面的字段。
`query.where` 的意义为：什么样的数据需要返回给客户端。

所以 `query.fields` 不能定义哪条数据需要返回给客户端，仅能定义返回给客户端的数据要保留哪些字段。

在 node.js 实现的 parse-server 中也是这么做的。

**Comment by lfq7413** [comment]
确实， parse-server wiki 中的这句话是有问题的，应该是：
If you are only interested in the `name` field of the object that has changed, you can set `query.fields` to `[name]`

在这句话：

> If you are only interested in the change of the name field, you can set query.fields to [name]

之后，还有一句话：

> In this situation, when the change of a Player ParseObject fulfills the subscription, only the name field will be sent to the clients instead of the full Player ParseObject.

意思是：当一个对象 fulfills the subscription 时，这个对象就会发送给客户端，同时这个对象中仅包含 `name` 这个字段。
严格来说，这句话应该是： when a Player ParseObject that has changed fulfills the subscription
