### ISSUE TITLE
ParseLiveQuery - increment problem

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#12]
after increment a number field instead of final result value the following code send to client

![image](https://cloud.githubusercontent.com/assets/14992986/22629312/d772d694-ebf8-11e6-8c64-943ce157fb56.png)

**Comment by lfq7413** [comment]
很抱歉，LiveQuery 中暂时不支持对 Increment 、 Add 、 AddUnique 、 Remove 、 AddRelation 、 RemoveRelation 、 Delete 这几种更新操作进行处理。
后续会增加对该功能的支持。

**Comment by ghost** [comment]
thanks, can you help me about which method needs to complete?

**Comment by lfq7413** [comment]
Increment 、 Add 、 AddUnique 、 Remove 、 AddRelation 、 RemoveRelation 、 Delete 这几种操作均会支持。将增加处理代码，模拟对应的数据库操作：
1. Increment 对 Number 类型的字段进行操作，在原始数据的基础上进行计数操作；
2. Add AddUnique Remove 对 Arrays 类型的字段进行操作，在原始数组的基础上进行加减元素的操作；
3. AddRelation RemoveRelation 对 Relation 类型的字段进行操作，该字段按照格式返回 {"__type":"Relation","className": "RelationClassName"} ；
4. Delete 意义即为删除该字段，所以在返回数据中直接删除该字段。

后续会实现以上 4 种逻辑。

**Comment by ghost** [comment]
I will test it

**Comment by ghost** [comment]
it's ok
