### ISSUE TITLE
simulate left join

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#13]
suppose we have post and like objects/collections, and I need to get list of posts with a additional/derived filed named as has_liked (a Boolean field that: true value means current user like the post and false value shows other states).  I think a solution is:
1) find a list of post and 
2) the derived field calculated and added to the results in the AfterFind could method.

I would be obliged if you kindly help me about such situation.

**Comment by ghost** [comment]
```golang

cloud.AfterFind("post", func(req cloud.TriggerRequest, resp cloud.Response) {
		objects := req.Objects
		
		ids := make(types.S, 0)
		// how to get current user?

		for _, o := range objects {
			if object := utils.M(o); object != nil {
				if oId, ok := object["objectId"].(string); ok {
					ids = append(ids, types.M{
						"__type":    "Pointer",
						"className": "post",
						"objectId":  oId,
					})
				}
			}
		}
		// restricts the query for
		// current user like?
		// and like of current post
		query := types.M{
			"pid": types.M{"$in": ids},
		}
		options := types.M{}
		results, err := orm.TomatoDBController.Find("like", query, options)
		if err != nil{
			resp.Error(0, err.Error())
		} else {
			fmt.Println(len(results))
			for _, r := range results {
				for _, o := range objects {
					if ro := utils.M(r); ro != nil {
						if object := utils.M(o); object != nil {
							object["has_liked"] = false
							if object["objectId"] == ro["pid"] {
								object["has_liked"] = true
							}
						}
					}
				}
			}
			resp.Success(objects)
		}
	})

```

**Comment by lfq7413** [comment]
当前用户信息保存在 `req.User` 中，包括 `objectId` `sessionToken` 等字段：
`objectId := req.User["objectId"]`

**Comment by lfq7413** [comment]
对于该问题，我有一种思路，不使用 `AfterFind` ：
首先在客户端中缓存用户已经 like 的 post ids ，
在每次获取 posts 之后，通过本地缓存去对比，然后添加 `has_liked` 字段，
当请求修改 like 状态之后，同步修改本地缓存。

本方法可以减少一次数据库操作，提升响应速度。在各种原生客户端中均可使用该方法。

但是对于使用 js 或其他不方便缓存数据的用户，有一点问题，因为不能缓存 post ids ，所以需要从应用中再发起一次请求，去获取已经 like 的 post ids 。

**Comment by lfq7413** [comment]
当然，你提供的算法也是完全可以实现需求的。不过还存在优化空间：
在 `results, err := orm.TomatoDBController.Find("like", query, options)` 之后，
循环遍历 `results` ，添加 post id 到 `map[string]boolean{}` 中，key 为 post 的 `objectId` ，value 为 true ，
然后遍历 `objects` ，从 `map[string]boolean{}` 中查询是否已经 like ，添加 `has_liked` 字段。

优化之后，减少了一层循环嵌套，复杂度从 m*n 变为 m+n 。

**Comment by ghost** [comment]
thanks
