### ISSUE TITLE
a question about clientID in LiveQueryServer 

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#14]
by considering the type of clientID, may it reach to max int?

**Comment by lfq7413** [comment]
int64 的最大值为： 9223372036854775807 ；
假设每秒钟有 1,000,000,000 个客户端连接过来；
那么理论上可以持续运行：
9223372036854775807/1000000000/60/60/24/365
= 292.4712 年

即：每秒 1,000,000,000 个客户端连接， 292.4712 年后 clientID 会达到最大值
