### ISSUE TITLE
online user

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#17]
suppose two users subscribe on a game object, is there any way to find when other user become offline or break the game? 
is leave ParseLiveQuery message useful for such situation?

**Comment by lfq7413** [comment]
先解释一下 leave ，假如订阅条件如下：
```json
{
	"op": "subscribe",
	"requestId": 1,
	"query": {
		"className": "Player",
		"where": {"name": "joe"}
	}
}
```
现在有一个对象：
```json
{
	"name": "joe"
}
```
修改 `name` 字段为 jack ，对象变成：
```json
{
	"name": "jack"
}
```
此时会收到 leave 事件：
```json
{
	"op": "leave",
	"requestId": 1,
	"object": {
		"className": "Player",
		"name": "jack"
	}
}
```

因此 leave 事件不能用于这个场景

**Comment by lfq7413** [comment]
在 LiveQuery 中，客户端上线与离线不会发出任何通知。但是可以通过其他方式间接达到这个目的。
比如：
1. 在客户端 A 中实现心跳机制，定时向一个表更新本客户端的信息
2. 在客户端 B 则通过 LiveQuery 订阅这个表的更新事件
3. 当客户端 B 超过一定时间没有收到更新事件时，则认为客户端 A 已离线
