### ISSUE TITLE
thread safe?

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#18]
which implementation is thread safe?
1.

```
cloud.AfterSave("collection", func(req cloud.TriggerRequest, resp cloud.Response) {
    go func() {
             reqObj := req.Object
             // ...
    }()
}
```

2.

```
cloud.AfterSave("collection", func(req cloud.TriggerRequest, resp cloud.Response) {
    go func() {
	  reqObj := utils.CopyMapM(req.Object)
          // ...
    }()
}
```

**Comment by lfq7413** [comment]
2 是线程安全的

**Comment by lfq7413** [comment]
utils.CopyMapM() 实现了简单的内存复制，在 req.Object 中仅包含基本数据类型，以及 map[string]interface{} 与 []interface{} 两种指针类型

所以 utils.CopyMapM() 可以完全复制数据，并且不包含任何引用。

**Comment by lfq7413** [comment]
当前线程在 write.go 中调用 `maybeRunTrigger(cloud.TypeAfterSave, w.auth, updatedObject, originalObject)` 之后，不会再对 updatedObject 与 originalObject 进行任何操作。

所以即使在其他线程中对 req.Object 进行非线程安全的操作，也不会出现问题。

**Comment by ghost** [comment]
> 当前线程在 write.go 中调用 maybeRunTrigger(cloud.TypeAfterSave, w.auth, updatedObject, originalObject) 之后，不会再对 updatedObject 与 originalObject 进行任何操作。
> 
> **_所以即使在其他线程中对 req.Object 进行非线程安全的操作，也不会出现问题。_**

it means that the first solution also is thread safe?

**Comment by lfq7413** [comment]
是的，在当前版本是这样的。
