### ISSUE TITLE
allowCrossDomain

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#2]
## in order to parse dashboard works correctly, the following methods must be add as middle-ware

// nodejs code:

export function allowCrossDomain(req, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
  res.header('Access-Control-Allow-Headers', 'X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, Content-Type');

  // intercept OPTIONS method
  if ('OPTIONS' == req.method) {
    res.sendStatus(200);
  }
  else {
    next();
  }
};

// -------------------------------------------------
// golang
// except file router
beego.InsertFilter("_", beego.BeforeRouter, cors.Allow(&cors.Options{
        AllowOrigins:     []string{"_"},
        AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
        AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin"},
        ExposeHeaders:    []string{"Access-Control-Allow-Headers","X-Parse-Master-Key", "X-Parse-REST-API-Key",
            "X-Parse-Javascript-Key", "X-Parse-Application-Id", "X-Parse-Client-Version", "X-Parse-Session-Token",
            "X-Requested-With", "X-Parse-Revocable-Session", "Content-Type"},
        AllowCredentials: true,
    }))

**Comment by lfq7413** [comment]
已添加 CrossDomain 支持，请测试一下吧

**Comment by ghost** [comment]
thanks, I check it with ParsePlatform/parse-dashboard

**Comment by ghost** [comment]
It's ok
