### ISSUE TITLE
Job example

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#20]
I would be obliged if you could kindly write a simple tutorial on job function.

**Comment by lfq7413** [comment]
job 的使用方式与云函数是类似的，区别是 job 函数在 goroutine 中执行。

所以在通过 /v1/jobs/:name 接口调用指定 job 之后，接口会立即返回成功。实际的 job 函数在后台继续运行。

当前在 tomato 中没有对 job 做计划运行的逻辑，因此在 job 函数中可自定义周期运行参数格式，并可根据客户端传入的参数周期运行指定功能。
