### ISSUE TITLE
Fileadapter

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#22]
If tomato server behind the ngunx, current implementation of file adapter returns private tomato server address. 
tomato/files/file_system_adapter.go ---» line 85

func (f *fileSystemAdapter) getFileLocation(filename string) string {
	return config.TConfig.ServerURL + "/files/" + config.TConfig.AppID + "/" + url.QueryEscape(filename)
}

**Comment by lfq7413** [comment]
文件下载链接：`config.TConfig.ServerURL + "/files/" + config.TConfig.AppID + "/" + url.QueryEscape(filename)` 实际上是由 tomato 进行处理。
处理代码位于：
https://github.com/lfq7413/tomato/blob/master/controllers/files.go#L28

所以，如果 tomato 位于 nginx 之后，只需要配置 config.TConfig.ServerURL 为正确的外网接口地址即可。
tomato 中的文件不是静态资源，不能使用 nginx 对外代理，实际上由 tomato 自身处理。

**Comment by ghost** [comment]
thanks, I will test it.
