### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by freeznet** [lfq7413/tomato#24]
使用postgres时登录出现密码错误，检查了下发现_User的schema中没有password，只有_hashed_password，于是乎在HandleLogIn函数中`correct := utils.Compare(password, utils.S(user["password"]))`这句检查出错，虽然有解决的方案，但是不确定怎么改是最合适的，所以发个issue求助一下~

**Comment by lfq7413** [comment]
我这边简单测试了一下注册和登录功能，没有出现这个问题。
@freeznet 可否详细说明一下你的操作步骤？

**Comment by lfq7413** [comment]
在 https://github.com/lfq7413/tomato/blob/master/orm/controller.go#L1140 对 _hashed_password 字段进行处理。

如果存在 _hashed_password 字段，则会转换成 password 字段。

**Comment by freeznet** [comment]
conf文件

```
appname = bajia-backend
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

ServerURL = http://127.0.0.1:8080/v1
DatabaseType = PostgreSQL
DatabaseURI = postgres://postgres@127.0.0.1:5432/bajia?sslmode=disable
AppID = test
MasterKey = test
ClientKey = test
JavaScriptKey = test
AllowClientClassCreation = true
```

使用全新的数据库，启动服务后，执行以下的request

```
## 注册用户
curl -X "POST" "http://127.0.0.1:8080/v1/users" \
     -H "X-Parse-Client-Key: test" \
     -H "X-Parse-Application-Id: test" \
     -H "Content-Type: application/json" \
     -d $'{
  "username": "guest",
  "password": "guest"
}'
```

返回结果

```
{
  "createdAt": "2017-06-14T04:54:06.378Z",
  "objectId": "5940c16ee5061f1351fea296",
  "sessionToken": "r:66A6E4248FD3F7C1D9A44A4BAFCE35BE"
}
```

然后再通过登录接口登录

```
curl "http://127.0.0.1:8080/v1/login" \
     -H "X-Parse-Client-Key: test" \
     -H "X-Parse-Application-Id: test" \
     -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
     -G \
         --data-urlencode 'username=guest' \
         --data-urlencode 'password=guest'
```

得到结果

```
{
  "code": 101,
  "error": "Invalid username/password."
}
```

然后输出了一下`HandleLogIn`中的`user`，发现有`_hashed_password`字段却没有`password`字段

**Comment by lfq7413** [comment]
如果是这种情况的话，这一行：
https://github.com/lfq7413/tomato/blob/master/orm/controller.go#L1140
没有走到，或者是 filterSensitiveData 就没有走到，请跟踪一下。

**Comment by freeznet** [comment]
跟踪了一下，发现是
https://github.com/lfq7413/tomato/blob/65b0aa94533c0c03f5807571386cc583c002307b/storage/postgres/PostgresStorageAdapter.go#L1376
这一行转换成`[]byte`的时候出错，ok==false，导致所有string的列都被删除了

**Comment by lfq7413** [comment]
我这边没有重现，所以只能是猜测。
我使用的数据库是 postgres 9.6，返回的数据类型应该均为 []byte 格式。

如果是转换失败的话，也会走 `object[fieldName] = nil` 这里，所以肯定会设置上 `object["_hashed_password"] = nil`
然后在 filterSensitiveData 中发现有 _hashed_password 字段的话，也会转换成 `object["password"] = nil`，所以 password 字段是肯定存在的。
如果不存在，还是需要跟踪一下为什么不存在 password 字段。

**Comment by freeznet** [comment]
不存在是因为
https://github.com/lfq7413/tomato/blob/65b0aa94533c0c03f5807571386cc583c002307b/storage/postgres/PostgresStorageAdapter.go#L1485
这里对nil的field进行了删除操作~

**Comment by lfq7413** [comment]
是的，这里对 nil 的 field 进行了删除操作，所以 _hashed_password 字段不会存在于 postgresObjectToParseObject 的返回结果里，也就不应该出现在 HandleLogIn 中的 user 中。

但是你在 HandleLogIn 中的 user 中观察到了 _hashed_password 。

这就出现矛盾了：
即，_hashed_password 字段的值在换成 []byte 的时候出错，导致字段被删除，但是在最终结果中又重新出现。

**Comment by lfq7413** [comment]
这样，这里的执行流程是，先执行 postgresObjectToParseObject 转换从数据库取的数据，然后通过 filterSensitiveData 处理 _User 表的数据，
所以只需要在这行：
https://github.com/lfq7413/tomato/blob/master/storage/postgres/PostgresStorageAdapter.go#L849
前后打印 object ，观察是否有 _hashed_password 字段，以及是否有值
在这行：
https://github.com/lfq7413/tomato/blob/master/orm/controller.go#L201
前后打印 object 与 result ，观察 _hashed_password 是否存在，以及 password 是否存在

观察差异即可找到问题所在。

**Comment by freeznet** [comment]
表述有误，打印user的时候应该是错把acl的数据中的一部分当做了_hashed_password，最后返回的user只有ACL updatedAt createdAt三个field

**Comment by lfq7413** [comment]
这样的话，就表示从数据库取出的 _hashed_password 字段的值不是 []byte 类型。_hashed_password 在存储的时候是 String 类型无疑， 在 schema 中也是定义的 String 类型。

@freeznet  其他 String 类型的字段是否也出错了？
是否能打印一下 _hashed_password 字段的原始值？或者去数据库看一下 _hashed_password 字段的值

**Comment by freeznet** [comment]
所有string类型的字段都会出错~

**Comment by lfq7413** [comment]
你的 postgres 版本是多少？lib/pq 库的版本是多少？

**Comment by freeznet** [comment]
postgres 测试了 两个版本 
PostgreSQL 9.6.3 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit
和
PostgreSQL 9.5.7 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit

lib/pq版本是当前master branch的 也就是通过`go get github.com/lib/pq`安装的

**Comment by lfq7413** [comment]
是否能打印一下 _hashed_password 字段的原始值，确定如果其不是 []byte 类型，那是什么类型，是不是
 string 类型？
或者去数据库看一下 _hashed_password 字段的值

**Comment by freeznet** [comment]
从数据库查询出来的结果
```
[
  {
    "_wperm" : "{5940da2ee5061f1fe0a052b2}",
    "updatedAt" : "2017-06-14 14:39:42.074+08",
    "_failed_login_count" : null,
    "createdAt" : "2017-06-14 14:39:42.074+08",
    "_email_verify_token_expires_at" : null,
    "_password_changed_at" : null,
    "_hashed_password" : "84983c60f7daadc1cb8698621f802c0d9f9a3c3c295c810748fb048115c186ec",
    "_perishable_token_expires_at" : null,
    "_email_verify_token" : null,
    "authData" : null,
    "emailVerified" : null,
    "_rperm" : "{*,5940da2ee5061f1fe0a052b2}",
    "username" : "guest",
    "objectId" : "5940da2ee5061f1fe0a052b2",
    "_perishable_token" : null,
    "_password_history" : null,
    "_account_lockout_expires_at" : null,
    "email" : null
  }
]
```

数据库表的结构
```
CREATE TABLE "_User" (
    _password_changed_at timestamp with time zone,
    "objectId" text NOT NULL,
    _email_verify_token_expires_at timestamp with time zone,
    _email_verify_token text,
    _perishable_token text,
    "authData" jsonb,
    _failed_login_count double precision,
    _password_history jsonb,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    _wperm text[],
    _hashed_password text,
    email text,
    _rperm text[],
    _account_lockout_expires_at timestamp with time zone,
    _perishable_token_expires_at timestamp with time zone,
    username text,
    "emailVerified" boolean
);
```

**Comment by freeznet** [comment]
在
https://github.com/lfq7413/tomato/blob/65b0aa94533c0c03f5807571386cc583c002307b/storage/postgres/PostgresStorageAdapter.go#L846
这里打印了查询到的值和对应的类型`log.Println("type:",field, *resultValues[i], reflect.TypeOf(*resultValues[i]))`

```
2017/06/14 14:50:44 type: _account_lockout_expires_at <nil> <nil>
2017/06/14 14:50:44 type: _perishable_token <nil> <nil>
2017/06/14 14:50:44 type: _password_history <nil> <nil>
2017/06/14 14:50:44 type: updatedAt 2017-06-14 14:39:42.074 +0800 CST time.Time
2017/06/14 14:50:44 type: _wperm [123 53 57 52 48 100 97 50 101 101 53 48 54 49 102 49 102 101 48 97 48 53 50 98 50 125] []uint8
2017/06/14 14:50:44 type: authData <nil> <nil>
2017/06/14 14:50:44 type: email <nil> <nil>
2017/06/14 14:50:44 type: _failed_login_count <nil> <nil>
2017/06/14 14:50:44 type: _perishable_token_expires_at <nil> <nil>
2017/06/14 14:50:44 type: createdAt 2017-06-14 14:39:42.074 +0800 CST time.Time
2017/06/14 14:50:44 type: objectId 5940da2ee5061f1fe0a052b2 string
2017/06/14 14:50:44 type: username guest string
2017/06/14 14:50:44 type: _email_verify_token_expires_at <nil> <nil>
2017/06/14 14:50:44 type: _email_verify_token <nil> <nil>
2017/06/14 14:50:44 type: _password_changed_at <nil> <nil>
2017/06/14 14:50:44 type: emailVerified <nil> <nil>
2017/06/14 14:50:44 type: _hashed_password 84983c60f7daadc1cb8698621f802c0d9f9a3c3c295c810748fb048115c186ec string
2017/06/14 14:50:44 type: _rperm [123 42 44 53 57 52 48 100 97 50 101 101 53 48 54 49 102 49 102 101 48 97 48 53 50 98 50 125] []uint8

```

**Comment by lfq7413** [comment]
发现问题了，新版本的 lib/pq 修改了返回数据的格式，从 []byte 变成了 string 类型。
go get -u -v github.com/lib/pq 更新之后重现了这个问题。

**Comment by lfq7413** [comment]
当时开发时使用的老版本 lib/pq ，欢迎继续提出相关问题。

**Comment by freeznet** [comment]
赞赞赞~
