### ISSUE TITLE
LiveQuery in online multiplayer game?

### ISSUE THREAD

**Issue by Yumcoder-dev** [lfq7413/tomato#25]
It is possible to use live query in a multiplayer game with the following conditions:

- the messages do not saved in any collection
- the players do not encountered any lag

**Comment by lfq7413** [comment]
暂时无法用于多人游戏。

LiveQuery 在修改数据时被触发，所以跟数据库有紧密的联系。

**Comment by Yumcoder-dev** [comment]
I would be grateful if you could give me your plan to support such feature?

**Comment by lfq7413** [comment]
LiveQuery 的机制决定了它不适合作为多人游戏的后端，LiveQuery 与数据库读写紧密相关，所以暂时没有计划去支持这个功能。

**Comment by m9rco** [comment]
说中文 好使吗

**Comment by lfq7413** [comment]
@PuShaoWei 还可以。

**Comment by m9rco** [comment]
@lfq7413 这个项目是干嘛用的，不是太清楚

**Comment by lfq7413** [comment]
@PuShaoWei 
Parse 是 Facebook 的产品，国内对应的产品有 [LeanCloud](https://leancloud.cn/) 、 [Bmob](https://www.bmob.cn/) 等。

这类产品作为应用的后端，可使移动端或者前端的应用开发者，无需进行后端开发，即可完成数据存储、文件存储等多个功能。

Parse 因为多种原因不再提供服务，所以 Facebook 对其进行了开源。原服务据说是使用 Go 开发的，但是 Go 版本并没有开源，[开源版本](https://github.com/parse-community/parse-server) 使用 JS 实现了所有功能，至今一直在维护。

本项目使用 Go 实现了 [Parse 开源版本](https://github.com/parse-community/parse-server) 几乎所有的功能。

**Comment by m9rco** [comment]
@lfq7413 
好吧，最近在用`beego`开发项目，想看些别人的最佳实践，我是搜`beego`的实例找到的,感觉好厉害的样子

**Comment by yumcoder-platform** [comment]
Is WebRTC is good for such situation?
If you have agreed, I would like to participate in implementation of such feature :-)

based on the above-mentioned platform the following features are recommended:
1- support multiplayer games
2- leaderboard 

3- SMS registration
4- ChatKit (considering https://www.mongodb.com/blog/post/schema-design-for-social-inboxes-in-mongodb)

implementation (Golang, Android and IOS SDK)

regards
