### ISSUE TITLE
mongo connection?

### ISSUE THREAD

**Issue by Yumcoder-dev** [lfq7413/tomato#27]
when is MongoDB connection closed?
I run the following command 

> _db.serverStatus().connections_

 in MongoDB to check the current connection, it seems after a client connects to the server and run a query the connection is opened and never closed.

**Comment by lfq7413** [comment]
tomato 使用了 gopkg.in/mgo.v2 去连接 MongoDB，在 mgo.v2 中使用了线程池，默认的最大连接数为4096 。

**Comment by lfq7413** [comment]
可以通过修改 DatabaseURI 中 maxPoolSize 参数来改变线程池的最大连接数。
