### ISSUE TITLE
parse-dashboard file upload

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#5]
in parse dash-board when connecting to tomato server, uploading a file encounter the following error:

XMLHttpRequest cannot load http://localhost:8080/v1/files/Screenshot%20from%202016-06-30%2023:06:44.png. **Request header field X-Parse-JavaScript-Key is not allowed by Access-Control-Allow-Headers in preflight response.**

**Comment by lfq7413** [comment]
@umdp 已修复该问题。
在 tomato 与 parse-dashboard 中需要配置 javascriptKey
然后从 http://0.0.0.0:4040/apps 重新进入 dashboard，javascriptKey 才能生效

**Comment by ghost** [comment]
it's ok, but in order to view file correctly in the parse-dashboard the following two points need to be fixed:
"/files/" must be change to "files/" 

```
func (f *fileSystemAdapter) getFileLocation(filename string) string {
    return config.TConfig.ServerURL + "files/" + config.TConfig.AppID + "/" + url.QueryEscape(filename)
}
```

```
func  (g *gridStoreAdapter) getFileLocation(filename string) string {
    return config.TConfig.ServerURL + "files/" + config.TConfig.AppID + "/" + url.QueryEscape(filename)
}
```

**Comment by lfq7413** [comment]
@gogile 在 tomato 中使用的 config.TConfig.ServerURL 格式一直为这样：http://127.0.0.1:8080/v1 ，但是 README.md 中为错误的 http://127.0.0.1:8080/v1/ 。已更正 README.md 中存在的问题，感谢！

**Comment by ghost** [comment]
it's ok.
