### ISSUE TITLE
livequery android sdk

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#7]
there is a bug in the following line when try to connect from the android sdk (https://github.com/TGIO/ParseLiveQuery) to livequery server:
tomato/livequery/server/WebSocketServer.go

// RunWebSocketServer ...
func RunWebSocketServer(pattern, addr string, h WebSocketHandler) {
	handler = h
	http.Handle(pattern, websocket.Handler(httpHandler))
	err := http.ListenAndServe(addr, nil)
	if err != nil {
		panic("ListenAndServe: " + err.Error())
	}
}

it is because exist a bug in the package "golang.org/x/net/websocket" 
in order to correct it the following line must be changed:
-------------------------------------
http.Handle(pattern, websocket.Handler(httpHandler))

chage to:
-------------------------------------
http.Handle(pattern, http.HandlerFunc(
		func (w http.ResponseWriter, req *http.Request) {
			s := websocket.Server{Handler: websocket.Handler(httpHandler)}
			s.ServeHTTP(w, req)
		}))

**Comment by ghost** [comment]
see the following link 
http://stackoverflow.com/questions/19708330/serving-a-websocket-in-go

**Comment by lfq7413** [comment]
另外，这算不上是 golang.org/x/net/websocket 的 bug ，因为 websocket 一开始就是应用于浏览器的技术，默认校验 Origin 也是合理的

**Comment by lfq7413** [comment]
另外，这算不上是 golang.org/x/net/websocket 的 bug ，因为 websocket 一开始就是应用于浏览器的技术，默认校验 Origin 也是合理的
