### ISSUE TITLE
type cast problem when call from android sdk

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#8]
the following line may be string when call from android sdk:
https://github.com/lfq7413/tomato/blob/master/controllers/classes.go#L181

also:
https://github.com/lfq7413/tomato/blob/master/controllers/classes.go#L193

**Comment by lfq7413** [comment]
Parse Android SDK 中的查询 API 实际上发起的是 POST 请求，body 中为 json 格式数据：
```
{
	"where": "{\"key\":\"value\"}",
	"skip": "10",
	"limit": "10",
	"_method": "GET"
}
```
首先在 tomato.go -> allowMethodOverride() 中进行了请求重载，POST > GET
其次在 controllers -> base.go -> Prepare() 中把 body 中的数据读取到了 Query 中：
https://github.com/lfq7413/tomato/blob/master/controllers/base.go#L149

所以最终处理 Android SDK 发起的查询请求的是以下这行：
https://github.com/lfq7413/tomato/blob/master/controllers/classes.go#L177
https://github.com/lfq7413/tomato/blob/master/controllers/classes.go#L187
