### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ghost** [lfq7413/tomato#9]
I would be obliged if you could kindly complete the following sections:
1- analytics
2- postgres adapter

regards

**Comment by lfq7413** [comment]
postgres 与 analytics 已经列入开发计划

**Comment by ghost** [comment]
so thanks for your current work in postgres. for analytics I recommend you to use  grafana.org and influxdb

**Comment by lfq7413** [comment]
@gogile 非常感谢你的建议！ grafana 很棒！后续会为分析模块添加 influxdb adapter

**Comment by ghost** [comment]
thanks for your current work in postgres.

**Comment by ghost** [comment]
Very very thanks, also for push adapter  I recommend you firebase and onesignal

**Comment by ghost** [comment]
What is your plane for push adapter?

**Comment by ghost** [comment]
When we can use the push adapter ?

**Comment by lfq7413** [comment]
push 模块已列入开发计划，可能会先支持 FCM
